source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'razorpay-pod_Example', :exclusive => true do
  pod 'razorpay-pod', :path => '../'
end

target 'razorpay-pod_Tests', :exclusive => true do
  pod 'razorpay-pod', :path => '../'

  
end
